### PR TITLE
Fix redirects with anchor links

### PR DESCRIPTION
**Pull request by iamqqv**
To redirect to urls with an anchor we need to force a reload

### CODE REVIEW

**Comment by felixkempf** [comment]
Wait a minute @jonathan-neugber @iamqqv 
The comment says it is for redirects with anchor, yet there is no condition whatsoever, so it is reloaded in every case. Is this really a desirable behavior?

**Comment by jonathan-neugber** [comment]
@felixkempf this forces a reload if none happens. If window.location triggers a page change no JS the `reload(true)` does nothing (at least according to specification). We tested it anyways and it worked so far.

**Comment by felixkempf** [comment]
Oh, so it's for the case that the redirect action is the same as the original, only the anchor changes?

**Comment by jonathan-neugber** [comment]
Depending on browser and version any url that contains a `#` will not trigger a redirect on setting `window.location`. So using the `reload(true)` is for those cases otherwise the browser will happily ignore it.

**Pull request merged**
